name = "feed-api"
compatibility_date = "2023-06-28"
main = "./src/index.ts"

[triggers]
crons = ["*/15 * * * *"]

[[r2_buckets]]
binding = "FEED_BUCKET"
bucket_name = "feed"
preview_bucket_name = "feed-preview"

[[r2_buckets]]
binding = "LOG_BUCKET"
bucket_name = "feed-log"
preview_bucket_name = "feed-log-preview"
